/*
 * generated by Xtext
 */
package org.shashwat.xtext.smallJava.ui.contentassist

import org.shashwat.xtext.smallJava.ui.contentassist.AbstractSmallJavaDslProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class SmallJavaDslProposalProvider extends AbstractSmallJavaDslProposalProvider {
}
