/*
 * generated by Xtext
 */
package org.shashwat.xtext.smallJava.ui.quickfix;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.ui.editor.model.IXtextDocument;
import org.eclipse.xtext.ui.editor.model.edit.IModification;
import org.eclipse.xtext.ui.editor.model.edit.IModificationContext;
import org.eclipse.xtext.ui.editor.model.edit.ISemanticModification;
import org.eclipse.xtext.ui.editor.quickfix.Fix;
import org.eclipse.xtext.ui.editor.quickfix.IssueResolutionAcceptor;
import org.eclipse.xtext.validation.Issue;
import org.shashwat.xtext.smallJava.smallJavaDsl.SmallJava;
import org.shashwat.xtext.smallJava.validation.IssueCodes;

/**
 * Custom quickfixes.
 *
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#quick-fixes
 */
public class SmallJavaDslQuickfixProvider extends org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider {

	@Fix(IssueCodes.INVALID_CLASS_NAME)
	public void quickFixForCheckClassNameShouldStartWithCapitalLetter(final Issue issue,
			IssueResolutionAcceptor acceptor) {
		acceptor.accept(issue, "Capatalize class name first char", 
				"Capatalize class name first char", "", new IModification() {
					
					@Override
					public void apply(IModificationContext context) throws Exception {
						final IXtextDocument xtextDocument = context.getXtextDocument();
						String firstChar = xtextDocument.get(issue.getOffset(), 1);
						xtextDocument.replace(issue.getOffset(), 1, firstChar.toUpperCase());
					}
				});
	}
	
	@Fix(IssueCodes.INVALID_ATTRIBUTE_NAME)
	public void quickFixForCheckAttributeShouldStartWithLowerLetter(final Issue issue,
			IssueResolutionAcceptor acceptor) {
		
	}
	
	@Fix(IssueCodes.INVALID_PARENT_NAME)
	public void quickFixForsmallClassCannotExtendAFinalClass(final Issue issue,
			IssueResolutionAcceptor acceptor) {
		acceptor.accept(issue, "Remove parent class", "Remove parent class", "", 
				new ISemanticModification() {
					
					@Override
					public void apply(EObject element, IModificationContext context) throws Exception {
						final SmallJava currentClass = (SmallJava) element;
						currentClass.setParent(null);
					}
				});
		
	}

}
